// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source contract.go -destination mocks_test.go -package reportservice_test
//

// Package reportservice_test is a generated GoMock package.
package report_test

import (
	context "context"
	reflect "reflect"

	models "github.com/YAMI4YOU/balance-service/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// FetchReport mocks base method.
func (m *Mockrepository) FetchReport(ctx context.Context, req models.Report) ([]models.ReportSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchReport", ctx, req)
	ret0, _ := ret[0].([]models.ReportSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchReport indicates an expected call of FetchReport.
func (mr *MockrepositoryMockRecorder) FetchReport(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchReport", reflect.TypeOf((*Mockrepository)(nil).FetchReport), ctx, req)
}

// Mockfile is a mock of file interface.
type Mockfile struct {
	ctrl     *gomock.Controller
	recorder *MockfileMockRecorder
	isgomock struct{}
}

// MockfileMockRecorder is the mock recorder for Mockfile.
type MockfileMockRecorder struct {
	mock *Mockfile
}

// NewMockfile creates a new mock instance.
func NewMockfile(ctrl *gomock.Controller) *Mockfile {
	mock := &Mockfile{ctrl: ctrl}
	mock.recorder = &MockfileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockfile) EXPECT() *MockfileMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *Mockfile) Save(model models.Report, summaries []models.ReportSummary) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", model, summaries)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockfileMockRecorder) Save(model, summaries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*Mockfile)(nil).Save), model, summaries)
}
