// Code generated by MockGen. DO NOT EDIT.
// Source: handler_test.go
//
// Generated by this command:
//
//	mockgen -source handler_test.go -destination mocks_test.go -package balance_test_test
//

// Package balance_test_test is a generated GoMock package.
package balance_test

import (
	context "context"
	reflect "reflect"

	models "github.com/YAMI4YOU/balance-service/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
	isgomock struct{}
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// FetchBalance mocks base method.
func (m *Mockrepo) FetchBalance(ctx context.Context, userID int) (models.Money, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchBalance", ctx, userID)
	ret0, _ := ret[0].(models.Money)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchBalance indicates an expected call of FetchBalance.
func (mr *MockrepoMockRecorder) FetchBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchBalance", reflect.TypeOf((*Mockrepo)(nil).FetchBalance), ctx, userID)
}
